# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindows.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDockWidget, QFrame,
    QGridLayout, QGroupBox, QLabel, QLineEdit,
    QMainWindow, QMenu, QMenuBar, QPlainTextEdit,
    QPushButton, QSizePolicy, QSpacerItem, QStatusBar,
    QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1180, 840)
        icon = QIcon()
        icon.addFile(u"icon/FeView_LogoL.ico", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        icon1 = QIcon()
        icon1.addFile(u"icon/Open.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionOpen.setIcon(icon1)
        self.actionEdit = QAction(MainWindow)
        self.actionEdit.setObjectName(u"actionEdit")
        icon2 = QIcon()
        icon2.addFile(u"icon/edit.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionEdit.setIcon(icon2)
        self.actionEdit_TCL = QAction(MainWindow)
        self.actionEdit_TCL.setObjectName(u"actionEdit_TCL")
        self.actionGray = QAction(MainWindow)
        self.actionGray.setObjectName(u"actionGray")
        self.actionGray.setCheckable(True)
        self.actionBlack = QAction(MainWindow)
        self.actionBlack.setObjectName(u"actionBlack")
        self.actionBlue = QAction(MainWindow)
        self.actionBlue.setObjectName(u"actionBlue")
        self.actionTheme_Color = QAction(MainWindow)
        self.actionTheme_Color.setObjectName(u"actionTheme_Color")
        icon3 = QIcon()
        icon3.addFile(u"icon/color_gui.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionTheme_Color.setIcon(icon3)
        self.actionGreen = QAction(MainWindow)
        self.actionGreen.setObjectName(u"actionGreen")
        self.actionNavy = QAction(MainWindow)
        self.actionNavy.setObjectName(u"actionNavy")
        self.actionViolet = QAction(MainWindow)
        self.actionViolet.setObjectName(u"actionViolet")
        self.actionPurple = QAction(MainWindow)
        self.actionPurple.setObjectName(u"actionPurple")
        self.actionOrchid = QAction(MainWindow)
        self.actionOrchid.setObjectName(u"actionOrchid")
        self.actionOlive = QAction(MainWindow)
        self.actionOlive.setObjectName(u"actionOlive")
        self.actionGold = QAction(MainWindow)
        self.actionGold.setObjectName(u"actionGold")
        self.actionTeal = QAction(MainWindow)
        self.actionTeal.setObjectName(u"actionTeal")
        self.actionSky_Blue = QAction(MainWindow)
        self.actionSky_Blue.setObjectName(u"actionSky_Blue")
        self.actionSteel_Blue = QAction(MainWindow)
        self.actionSteel_Blue.setObjectName(u"actionSteel_Blue")
        self.actionPink = QAction(MainWindow)
        self.actionPink.setObjectName(u"actionPink")
        self.actionWhite = QAction(MainWindow)
        self.actionWhite.setObjectName(u"actionWhite")
        self.actionGUI_Font = QAction(MainWindow)
        self.actionGUI_Font.setObjectName(u"actionGUI_Font")
        icon4 = QIcon()
        icon4.addFile(u"icon/font.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionGUI_Font.setIcon(icon4)
        self.actionPlot_Background_Color = QAction(MainWindow)
        self.actionPlot_Background_Color.setObjectName(u"actionPlot_Background_Color")
        icon5 = QIcon()
        icon5.addFile(u"icon/color_plot_background.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPlot_Background_Color.setIcon(icon5)
        self.actionMinimize = QAction(MainWindow)
        self.actionMinimize.setObjectName(u"actionMinimize")
        icon6 = QIcon()
        icon6.addFile(u"icon/minimize.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMinimize.setIcon(icon6)
        self.actionMaximize = QAction(MainWindow)
        self.actionMaximize.setObjectName(u"actionMaximize")
        icon7 = QIcon()
        icon7.addFile(u"icon/maximize.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMaximize.setIcon(icon7)
        self.actionFull_Screen = QAction(MainWindow)
        self.actionFull_Screen.setObjectName(u"actionFull_Screen")
        icon8 = QIcon()
        icon8.addFile(u"icon/full_s.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionFull_Screen.setIcon(icon8)
        self.actionCenter = QAction(MainWindow)
        self.actionCenter.setObjectName(u"actionCenter")
        icon9 = QIcon()
        icon9.addFile(u"icon/center.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCenter.setIcon(icon9)
        self.actionMinimum_Size = QAction(MainWindow)
        self.actionMinimum_Size.setObjectName(u"actionMinimum_Size")
        icon10 = QIcon()
        icon10.addFile(u"icon/min.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMinimum_Size.setIcon(icon10)
        self.actionMaximum_Size = QAction(MainWindow)
        self.actionMaximum_Size.setObjectName(u"actionMaximum_Size")
        icon11 = QIcon()
        icon11.addFile(u"icon/max.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMaximum_Size.setIcon(icon11)
        self.actionRestore = QAction(MainWindow)
        self.actionRestore.setObjectName(u"actionRestore")
        icon12 = QIcon()
        icon12.addFile(u"icon/rest_w.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionRestore.setIcon(icon12)
        self.actionSSL = QAction(MainWindow)
        self.actionSSL.setObjectName(u"actionSSL")
        icon13 = QIcon()
        icon13.addFile(u"icon/help.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSSL.setIcon(icon13)
        self.actionImage = QAction(MainWindow)
        self.actionImage.setObjectName(u"actionImage")
        self.actionNode_Label = QAction(MainWindow)
        self.actionNode_Label.setObjectName(u"actionNode_Label")
        icon14 = QIcon()
        icon14.addFile(u"icon/nl.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionNode_Label.setIcon(icon14)
        self.actionNode_Coordinate = QAction(MainWindow)
        self.actionNode_Coordinate.setObjectName(u"actionNode_Coordinate")
        icon15 = QIcon()
        icon15.addFile(u"icon/nc.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionNode_Coordinate.setIcon(icon15)
        self.actionLoad = QAction(MainWindow)
        self.actionLoad.setObjectName(u"actionLoad")
        icon16 = QIcon()
        icon16.addFile(u"icon/load.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionLoad.setIcon(icon16)
        self.actionIsometric = QAction(MainWindow)
        self.actionIsometric.setObjectName(u"actionIsometric")
        icon17 = QIcon()
        icon17.addFile(u"icon/iso.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionIsometric.setIcon(icon17)
        self.actionxy_zpluss = QAction(MainWindow)
        self.actionxy_zpluss.setObjectName(u"actionxy_zpluss")
        icon18 = QIcon()
        icon18.addFile(u"icon/xy_zpluss.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionxy_zpluss.setIcon(icon18)
        self.actionxy_zminus = QAction(MainWindow)
        self.actionxy_zminus.setObjectName(u"actionxy_zminus")
        icon19 = QIcon()
        icon19.addFile(u"icon/xy_zminus.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionxy_zminus.setIcon(icon19)
        self.actionXZ_Plane_Y = QAction(MainWindow)
        self.actionXZ_Plane_Y.setObjectName(u"actionXZ_Plane_Y")
        icon20 = QIcon()
        icon20.addFile(u"icon/xz_ypluss.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionXZ_Plane_Y.setIcon(icon20)
        self.actionXZ_Plane_Y_2 = QAction(MainWindow)
        self.actionXZ_Plane_Y_2.setObjectName(u"actionXZ_Plane_Y_2")
        icon21 = QIcon()
        icon21.addFile(u"icon/xz_yminus.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionXZ_Plane_Y_2.setIcon(icon21)
        self.actionYZ_Plane_X = QAction(MainWindow)
        self.actionYZ_Plane_X.setObjectName(u"actionYZ_Plane_X")
        icon22 = QIcon()
        icon22.addFile(u"icon/yz_xpluss.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionYZ_Plane_X.setIcon(icon22)
        self.actionYZ_Plane_X_2 = QAction(MainWindow)
        self.actionYZ_Plane_X_2.setObjectName(u"actionYZ_Plane_X_2")
        icon23 = QIcon()
        icon23.addFile(u"icon/yz_xminus.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionYZ_Plane_X_2.setIcon(icon23)
        self.actionExport_Report = QAction(MainWindow)
        self.actionExport_Report.setObjectName(u"actionExport_Report")
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        icon24 = QIcon()
        icon24.addFile(u"icon/close.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionExit.setIcon(icon24)
        self.actionRun_OpenSees = QAction(MainWindow)
        self.actionRun_OpenSees.setObjectName(u"actionRun_OpenSees")
        icon25 = QIcon()
        icon25.addFile(u"icon/run.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionRun_OpenSees.setIcon(icon25)
        self.actionApply_Static = QAction(MainWindow)
        self.actionApply_Static.setObjectName(u"actionApply_Static")
        self.actionShow_Response = QAction(MainWindow)
        self.actionShow_Response.setObjectName(u"actionShow_Response")
        self.actionApply_Modal = QAction(MainWindow)
        self.actionApply_Modal.setObjectName(u"actionApply_Modal")
        self.actionApply_dynamic = QAction(MainWindow)
        self.actionApply_dynamic.setObjectName(u"actionApply_dynamic")
        self.actionShow_Response_dynamic = QAction(MainWindow)
        self.actionShow_Response_dynamic.setObjectName(u"actionShow_Response_dynamic")
        self.actionOpenSees = QAction(MainWindow)
        self.actionOpenSees.setObjectName(u"actionOpenSees")
        icon26 = QIcon()
        icon26.addFile(u"icon/os.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionOpenSees.setIcon(icon26)
        self.actionFeView = QAction(MainWindow)
        self.actionFeView.setObjectName(u"actionFeView")
        icon27 = QIcon()
        icon27.addFile(u"icon/info.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionFeView.setIcon(icon27)
        self.actionWith_background = QAction(MainWindow)
        self.actionWith_background.setObjectName(u"actionWith_background")
        icon28 = QIcon()
        icon28.addFile(u"icon/plot_image.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionWith_background.setIcon(icon28)
        self.actionWhite_Background = QAction(MainWindow)
        self.actionWhite_Background.setObjectName(u"actionWhite_Background")
        icon29 = QIcon()
        icon29.addFile(u"icon/plot_image_wb.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionWhite_Background.setIcon(icon29)
        self.actionMesh_Fiew = QAction(MainWindow)
        self.actionMesh_Fiew.setObjectName(u"actionMesh_Fiew")
        self.actionMesh_Fiew.setCheckable(True)
        self.actionMesh_Fiew.setChecked(True)
        icon30 = QIcon()
        icon30.addFile(u"icon/mesh.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMesh_Fiew.setIcon(icon30)
        self.actionSmooth_View = QAction(MainWindow)
        self.actionSmooth_View.setObjectName(u"actionSmooth_View")
        self.actionSmooth_View.setCheckable(True)
        icon31 = QIcon()
        icon31.addFile(u"icon/smooth.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSmooth_View.setIcon(icon31)
        self.actionWireframe = QAction(MainWindow)
        self.actionWireframe.setObjectName(u"actionWireframe")
        self.actionWireframe.setCheckable(True)
        icon32 = QIcon()
        icon32.addFile(u"icon/wire.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionWireframe.setIcon(icon32)
        self.actionMesh_View_Wiremesh = QAction(MainWindow)
        self.actionMesh_View_Wiremesh.setObjectName(u"actionMesh_View_Wiremesh")
        self.actionMesh_View_Wiremesh.setCheckable(True)
        self.actionSmooth_View_Wiremesh = QAction(MainWindow)
        self.actionSmooth_View_Wiremesh.setObjectName(u"actionSmooth_View_Wiremesh")
        self.actionSmooth_View_Wiremesh.setCheckable(True)
        self.actionMesh_View_2 = QAction(MainWindow)
        self.actionMesh_View_2.setObjectName(u"actionMesh_View_2")
        self.actionMesh_View_2.setCheckable(True)
        self.actionMesh_View_2.setChecked(True)
        icon33 = QIcon()
        icon33.addFile(u"icon/rmesh.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMesh_View_2.setIcon(icon33)
        self.actionSmooth_View_2 = QAction(MainWindow)
        self.actionSmooth_View_2.setObjectName(u"actionSmooth_View_2")
        self.actionSmooth_View_2.setCheckable(True)
        icon34 = QIcon()
        icon34.addFile(u"icon/rsmooth.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSmooth_View_2.setIcon(icon34)
        self.actionMesh_View_Wiremesh_undeform = QAction(MainWindow)
        self.actionMesh_View_Wiremesh_undeform.setObjectName(u"actionMesh_View_Wiremesh_undeform")
        self.actionMesh_View_Wiremesh_undeform.setCheckable(True)
        icon35 = QIcon()
        icon35.addFile(u"icon/mesh_w.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMesh_View_Wiremesh_undeform.setIcon(icon35)
        self.actionSmooth_View_Wiremesh_undeform = QAction(MainWindow)
        self.actionSmooth_View_Wiremesh_undeform.setObjectName(u"actionSmooth_View_Wiremesh_undeform")
        self.actionSmooth_View_Wiremesh_undeform.setCheckable(True)
        icon36 = QIcon()
        icon36.addFile(u"icon/smooth_w.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSmooth_View_Wiremesh_undeform.setIcon(icon36)
        self.actionLoad_Setting = QAction(MainWindow)
        self.actionLoad_Setting.setObjectName(u"actionLoad_Setting")
        self.actionView_load = QAction(MainWindow)
        self.actionView_load.setObjectName(u"actionView_load")
        self.actionView_load.setCheckable(True)
        self.actionView_Support = QAction(MainWindow)
        self.actionView_Support.setObjectName(u"actionView_Support")
        self.actionView_Support.setCheckable(True)
        self.actionView_Support.setChecked(True)
        self.actionData_Table = QAction(MainWindow)
        self.actionData_Table.setObjectName(u"actionData_Table")
        self.actionData_Table_modal = QAction(MainWindow)
        self.actionData_Table_modal.setObjectName(u"actionData_Table_modal")
        self.actionData_Table_dynamic = QAction(MainWindow)
        self.actionData_Table_dynamic.setObjectName(u"actionData_Table_dynamic")
        self.actionFeView_Website = QAction(MainWindow)
        self.actionFeView_Website.setObjectName(u"actionFeView_Website")
        self.actionSSL_Website = QAction(MainWindow)
        self.actionSSL_Website.setObjectName(u"actionSSL_Website")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 15, 0)
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setStyleSheet(u"border: 3px solid green;\n"
"margin:0px,0px,0px,0px;\n"
"padding: 0px;")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Plain)
        self.frame.setLineWidth(2)

        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1180, 21))
        self.menuFIle = QMenu(self.menubar)
        self.menuFIle.setObjectName(u"menuFIle")
        self.menuExport_Plot = QMenu(self.menuFIle)
        self.menuExport_Plot.setObjectName(u"menuExport_Plot")
        self.menuExport_Plot.setIcon(icon28)
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuModel_View_Style = QMenu(self.menuEdit)
        self.menuModel_View_Style.setObjectName(u"menuModel_View_Style")
        self.menuModel_View_Style.setIcon(icon30)
        self.menuDeform_Model_Display_Style = QMenu(self.menuEdit)
        self.menuDeform_Model_Display_Style.setObjectName(u"menuDeform_Model_Display_Style")
        self.menuDeform_Model_Display_Style.setIcon(icon33)
        self.menuEdit_2 = QMenu(self.menubar)
        self.menuEdit_2.setObjectName(u"menuEdit_2")
        self.menuStattic_Analysis = QMenu(self.menuEdit_2)
        self.menuStattic_Analysis.setObjectName(u"menuStattic_Analysis")
        icon37 = QIcon()
        icon37.addFile(u"icon/static.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menuStattic_Analysis.setIcon(icon37)
        self.menuModal_Analysis = QMenu(self.menuEdit_2)
        self.menuModal_Analysis.setObjectName(u"menuModal_Analysis")
        icon38 = QIcon()
        icon38.addFile(u"icon/modal.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menuModal_Analysis.setIcon(icon38)
        self.Apply_Dyanamic = QMenu(self.menuEdit_2)
        self.Apply_Dyanamic.setObjectName(u"Apply_Dyanamic")
        icon39 = QIcon()
        icon39.addFile(u"icon/dynamic.png", QSize(), QIcon.Normal, QIcon.Off)
        self.Apply_Dyanamic.setIcon(icon39)
        self.menuWindows = QMenu(self.menubar)
        self.menuWindows.setObjectName(u"menuWindows")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuAbout = QMenu(self.menubar)
        self.menuAbout.setObjectName(u"menuAbout")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuLabel = QMenu(self.menuView)
        self.menuLabel.setObjectName(u"menuLabel")
        self.menuLabel.setIcon(icon14)
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QDockWidget(MainWindow)
        self.dockWidget.setObjectName(u"dockWidget")
        self.dockWidget.setMinimumSize(QSize(230, 599))
        self.dockWidget.setMaximumSize(QSize(230, 800))
        self.dockWidget.setMouseTracking(False)
        self.dockWidget.setTabletTracking(False)
        self.dockWidget.setFocusPolicy(Qt.StrongFocus)
        self.dockWidget.setFloating(False)
        self.dockWidget.setFeatures(QDockWidget.DockWidgetFloatable|QDockWidget.DockWidgetMovable)
        self.dockWidgetContents_2 = QWidget()
        self.dockWidgetContents_2.setObjectName(u"dockWidgetContents_2")
        self.verticalLayout = QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(5, 5, 5, 0)
        self.groupBox_8 = QGroupBox(self.dockWidgetContents_2)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.gridLayout_3 = QGridLayout(self.groupBox_8)
        self.gridLayout_3.setSpacing(2)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(5, 2, 5, 2)
        self.label_2 = QLabel(self.groupBox_8)
        self.label_2.setObjectName(u"label_2")

        self.gridLayout_3.addWidget(self.label_2, 0, 1, 1, 1)

        self.tb_sef_scale_factor = QLineEdit(self.groupBox_8)
        self.tb_sef_scale_factor.setObjectName(u"tb_sef_scale_factor")

        self.gridLayout_3.addWidget(self.tb_sef_scale_factor, 0, 2, 1, 1)


        self.verticalLayout.addWidget(self.groupBox_8)

        self.groupBox_2 = QGroupBox(self.dockWidgetContents_2)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.verticalLayout_2 = QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(2, 0, 2, 2)
        self.groupBox_3 = QGroupBox(self.groupBox_2)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.gridLayout_2 = QGridLayout(self.groupBox_3)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(5, 2, 5, 2)
        self.label_3 = QLabel(self.groupBox_3)
        self.label_3.setObjectName(u"label_3")

        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)

        self.cb_node_contour_static = QComboBox(self.groupBox_3)
        self.cb_node_contour_static.setObjectName(u"cb_node_contour_static")
        self.cb_node_contour_static.setMinimumSize(QSize(140, 0))

        self.gridLayout_2.addWidget(self.cb_node_contour_static, 2, 1, 1, 2)


        self.verticalLayout_2.addWidget(self.groupBox_3)

        self.groupBox_6 = QGroupBox(self.groupBox_2)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setStyleSheet(u"")
        self.groupBox_6.setFlat(True)
        self.gridLayout_9 = QGridLayout(self.groupBox_6)
        self.gridLayout_9.setObjectName(u"gridLayout_9")
        self.gridLayout_9.setHorizontalSpacing(5)
        self.gridLayout_9.setVerticalSpacing(0)
        self.gridLayout_9.setContentsMargins(0, 5, 0, 5)
        self.btn_apply_static = QPushButton(self.groupBox_6)
        self.btn_apply_static.setObjectName(u"btn_apply_static")
        self.btn_apply_static.setCheckable(True)

        self.gridLayout_9.addWidget(self.btn_apply_static, 0, 0, 1, 1)

        self.btn_response_static = QPushButton(self.groupBox_6)
        self.btn_response_static.setObjectName(u"btn_response_static")
        self.btn_response_static.setMaximumSize(QSize(16777215, 16777215))
        self.btn_response_static.setLayoutDirection(Qt.RightToLeft)
        self.btn_response_static.setStyleSheet(u"")
        self.btn_response_static.setIconSize(QSize(32, 16))
        self.btn_response_static.setFlat(False)

        self.gridLayout_9.addWidget(self.btn_response_static, 0, 1, 1, 1)

        self.btn_datatable_static = QPushButton(self.groupBox_6)
        self.btn_datatable_static.setObjectName(u"btn_datatable_static")

        self.gridLayout_9.addWidget(self.btn_datatable_static, 0, 2, 1, 1)


        self.verticalLayout_2.addWidget(self.groupBox_6)


        self.verticalLayout.addWidget(self.groupBox_2)

        self.groupBox_5 = QGroupBox(self.dockWidgetContents_2)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.gridLayout_4 = QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.label = QLabel(self.groupBox_5)
        self.label.setObjectName(u"label")
        self.label.setMaximumSize(QSize(90, 16777215))

        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)

        self.btn_apply_modal = QPushButton(self.groupBox_5)
        self.btn_apply_modal.setObjectName(u"btn_apply_modal")
        self.btn_apply_modal.setCheckable(True)

        self.gridLayout_4.addWidget(self.btn_apply_modal, 3, 0, 1, 1)

        self.btn_datatable_modal = QPushButton(self.groupBox_5)
        self.btn_datatable_modal.setObjectName(u"btn_datatable_modal")

        self.gridLayout_4.addWidget(self.btn_datatable_modal, 3, 2, 1, 1)

        self.groupBox_4 = QGroupBox(self.groupBox_5)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.gridLayout_7 = QGridLayout(self.groupBox_4)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.gridLayout_7.setContentsMargins(2, 0, 2, 2)
        self.label_5 = QLabel(self.groupBox_4)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setMaximumSize(QSize(90, 16777215))

        self.gridLayout_7.addWidget(self.label_5, 0, 0, 1, 1)

        self.cb_node_contour_modal = QComboBox(self.groupBox_4)
        self.cb_node_contour_modal.addItem("")
        self.cb_node_contour_modal.addItem("")
        self.cb_node_contour_modal.addItem("")
        self.cb_node_contour_modal.addItem("")
        self.cb_node_contour_modal.setObjectName(u"cb_node_contour_modal")
        self.cb_node_contour_modal.setMinimumSize(QSize(0, 0))

        self.gridLayout_7.addWidget(self.cb_node_contour_modal, 0, 1, 1, 1)


        self.gridLayout_4.addWidget(self.groupBox_4, 2, 0, 1, 3)

        self.cb_numNodes = QComboBox(self.groupBox_5)
        self.cb_numNodes.setObjectName(u"cb_numNodes")
        self.cb_numNodes.setMinimumSize(QSize(0, 0))

        self.gridLayout_4.addWidget(self.cb_numNodes, 0, 1, 1, 2)


        self.verticalLayout.addWidget(self.groupBox_5)

        self.groupBox_7 = QGroupBox(self.dockWidgetContents_2)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.gridLayout_10 = QGridLayout(self.groupBox_7)
        self.gridLayout_10.setObjectName(u"gridLayout_10")
        self.gridLayout_10.setContentsMargins(5, 2, 5, 2)
        self.label_4 = QLabel(self.groupBox_7)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setMaximumSize(QSize(90, 16777215))

        self.gridLayout_10.addWidget(self.label_4, 0, 0, 1, 1)

        self.label_6 = QLabel(self.groupBox_7)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setMaximumSize(QSize(90, 16777215))

        self.gridLayout_10.addWidget(self.label_6, 1, 0, 1, 1)

        self.cb_steps_dynamic = QComboBox(self.groupBox_7)
        self.cb_steps_dynamic.setObjectName(u"cb_steps_dynamic")
        self.cb_steps_dynamic.setMinimumSize(QSize(0, 0))
        self.cb_steps_dynamic.setMaximumSize(QSize(140, 16777215))

        self.gridLayout_10.addWidget(self.cb_steps_dynamic, 0, 1, 1, 1)

        self.groupBox_14 = QGroupBox(self.groupBox_7)
        self.groupBox_14.setObjectName(u"groupBox_14")
        self.groupBox_14.setStyleSheet(u"")
        self.groupBox_14.setFlat(True)
        self.gridLayout_13 = QGridLayout(self.groupBox_14)
        self.gridLayout_13.setObjectName(u"gridLayout_13")
        self.gridLayout_13.setHorizontalSpacing(5)
        self.gridLayout_13.setVerticalSpacing(0)
        self.gridLayout_13.setContentsMargins(0, 5, 0, 5)
        self.btn_datatable_dynamic = QPushButton(self.groupBox_14)
        self.btn_datatable_dynamic.setObjectName(u"btn_datatable_dynamic")

        self.gridLayout_13.addWidget(self.btn_datatable_dynamic, 0, 2, 1, 1)

        self.btn_response_dynamic = QPushButton(self.groupBox_14)
        self.btn_response_dynamic.setObjectName(u"btn_response_dynamic")
        self.btn_response_dynamic.setMaximumSize(QSize(16777215, 16777215))
        self.btn_response_dynamic.setLayoutDirection(Qt.RightToLeft)
        self.btn_response_dynamic.setIconSize(QSize(32, 16))
        self.btn_response_dynamic.setFlat(False)

        self.gridLayout_13.addWidget(self.btn_response_dynamic, 0, 1, 1, 1)

        self.btn_apply_dynamic = QPushButton(self.groupBox_14)
        self.btn_apply_dynamic.setObjectName(u"btn_apply_dynamic")
        self.btn_apply_dynamic.setCheckable(True)

        self.gridLayout_13.addWidget(self.btn_apply_dynamic, 0, 0, 1, 1)


        self.gridLayout_10.addWidget(self.groupBox_14, 2, 0, 1, 2)

        self.cb_node_contour_dynamic = QComboBox(self.groupBox_7)
        self.cb_node_contour_dynamic.setObjectName(u"cb_node_contour_dynamic")
        self.cb_node_contour_dynamic.setMaximumSize(QSize(140, 16777215))

        self.gridLayout_10.addWidget(self.cb_node_contour_dynamic, 1, 1, 1, 1)


        self.verticalLayout.addWidget(self.groupBox_7)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout.addItem(self.verticalSpacer)

        self.groupBox = QGroupBox(self.dockWidgetContents_2)
        self.groupBox.setObjectName(u"groupBox")
        self.verticalLayout_3 = QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.reportEdit = QPlainTextEdit(self.groupBox)
        self.reportEdit.setObjectName(u"reportEdit")

        self.verticalLayout_3.addWidget(self.reportEdit)

        self.groupBox_9 = QGroupBox(self.groupBox)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.verticalLayout_4 = QVBoxLayout(self.groupBox_9)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.reportEdit_2 = QPlainTextEdit(self.groupBox_9)
        self.reportEdit_2.setObjectName(u"reportEdit_2")
        self.reportEdit_2.setMaximumSize(QSize(16777215, 50))

        self.verticalLayout_4.addWidget(self.reportEdit_2)


        self.verticalLayout_3.addWidget(self.groupBox_9)


        self.verticalLayout.addWidget(self.groupBox)

        self.dockWidget.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(Qt.LeftDockWidgetArea, self.dockWidget)

        self.menubar.addAction(self.menuFIle.menuAction())
        self.menubar.addAction(self.menuEdit_2.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuWindows.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menuFIle.addAction(self.actionOpen)
        self.menuFIle.addAction(self.actionEdit)
        self.menuFIle.addSeparator()
        self.menuFIle.addAction(self.menuExport_Plot.menuAction())
        self.menuFIle.addAction(self.actionExit)
        self.menuFIle.addAction(self.actionSave)
        self.menuExport_Plot.addAction(self.actionWith_background)
        self.menuExport_Plot.addAction(self.actionWhite_Background)
        self.menuEdit.addAction(self.menuModel_View_Style.menuAction())
        self.menuEdit.addAction(self.menuDeform_Model_Display_Style.menuAction())
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionView_load)
        self.menuEdit.addAction(self.actionView_Support)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionPlot_Background_Color)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionGUI_Font)
        self.menuEdit.addAction(self.actionTheme_Color)
        self.menuEdit.addSeparator()
        self.menuModel_View_Style.addAction(self.actionMesh_Fiew)
        self.menuModel_View_Style.addAction(self.actionSmooth_View)
        self.menuModel_View_Style.addAction(self.actionWireframe)
        self.menuDeform_Model_Display_Style.addAction(self.actionMesh_View_2)
        self.menuDeform_Model_Display_Style.addAction(self.actionSmooth_View_2)
        self.menuDeform_Model_Display_Style.addAction(self.actionMesh_View_Wiremesh_undeform)
        self.menuDeform_Model_Display_Style.addAction(self.actionSmooth_View_Wiremesh_undeform)
        self.menuEdit_2.addAction(self.actionRun_OpenSees)
        self.menuEdit_2.addAction(self.menuStattic_Analysis.menuAction())
        self.menuEdit_2.addAction(self.menuModal_Analysis.menuAction())
        self.menuEdit_2.addAction(self.Apply_Dyanamic.menuAction())
        self.menuStattic_Analysis.addAction(self.actionApply_Static)
        self.menuStattic_Analysis.addAction(self.actionShow_Response)
        self.menuStattic_Analysis.addAction(self.actionData_Table)
        self.menuModal_Analysis.addAction(self.actionApply_Modal)
        self.menuModal_Analysis.addAction(self.actionData_Table_modal)
        self.Apply_Dyanamic.addAction(self.actionApply_dynamic)
        self.Apply_Dyanamic.addAction(self.actionShow_Response_dynamic)
        self.Apply_Dyanamic.addAction(self.actionData_Table_dynamic)
        self.menuWindows.addAction(self.actionMinimize)
        self.menuWindows.addAction(self.actionMaximize)
        self.menuWindows.addAction(self.actionFull_Screen)
        self.menuWindows.addAction(self.actionCenter)
        self.menuWindows.addAction(self.actionMinimum_Size)
        self.menuWindows.addAction(self.actionMaximum_Size)
        self.menuWindows.addAction(self.actionRestore)
        self.menuHelp.addAction(self.actionSSL)
        self.menuHelp.addAction(self.actionOpenSees)
        self.menuAbout.addAction(self.actionFeView)
        self.menuAbout.addAction(self.actionFeView_Website)
        self.menuAbout.addAction(self.actionSSL_Website)
        self.menuView.addAction(self.menuLabel.menuAction())
        self.menuView.addAction(self.actionLoad)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionIsometric)
        self.menuView.addAction(self.actionxy_zpluss)
        self.menuView.addAction(self.actionxy_zminus)
        self.menuView.addAction(self.actionXZ_Plane_Y)
        self.menuView.addAction(self.actionXZ_Plane_Y_2)
        self.menuView.addAction(self.actionYZ_Plane_X)
        self.menuView.addAction(self.actionYZ_Plane_X_2)
        self.menuView.addSeparator()
        self.menuLabel.addAction(self.actionNode_Label)
        self.menuLabel.addAction(self.actionNode_Coordinate)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"FeView", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionEdit.setText(QCoreApplication.translate("MainWindow", u"Edit TCL", None))
        self.actionEdit_TCL.setText(QCoreApplication.translate("MainWindow", u"Edit TCL", None))
        self.actionGray.setText(QCoreApplication.translate("MainWindow", u"Default", None))
        self.actionBlack.setText(QCoreApplication.translate("MainWindow", u"Black", None))
        self.actionBlue.setText(QCoreApplication.translate("MainWindow", u"Blue", None))
        self.actionTheme_Color.setText(QCoreApplication.translate("MainWindow", u"GUI Color", None))
        self.actionGreen.setText(QCoreApplication.translate("MainWindow", u"Green", None))
        self.actionNavy.setText(QCoreApplication.translate("MainWindow", u"Navy", None))
        self.actionViolet.setText(QCoreApplication.translate("MainWindow", u"Violet", None))
        self.actionPurple.setText(QCoreApplication.translate("MainWindow", u"Purple", None))
        self.actionOrchid.setText(QCoreApplication.translate("MainWindow", u"Orchid", None))
        self.actionOlive.setText(QCoreApplication.translate("MainWindow", u"Olive", None))
        self.actionGold.setText(QCoreApplication.translate("MainWindow", u"Gold", None))
        self.actionTeal.setText(QCoreApplication.translate("MainWindow", u"Teal", None))
        self.actionSky_Blue.setText(QCoreApplication.translate("MainWindow", u"Sky Blue", None))
        self.actionSteel_Blue.setText(QCoreApplication.translate("MainWindow", u"Steel Blue", None))
        self.actionPink.setText(QCoreApplication.translate("MainWindow", u"Pink", None))
        self.actionWhite.setText(QCoreApplication.translate("MainWindow", u"White", None))
        self.actionGUI_Font.setText(QCoreApplication.translate("MainWindow", u"Font", None))
        self.actionPlot_Background_Color.setText(QCoreApplication.translate("MainWindow", u"Plot Background Color", None))
        self.actionMinimize.setText(QCoreApplication.translate("MainWindow", u"Minimise", None))
        self.actionMaximize.setText(QCoreApplication.translate("MainWindow", u"Maximize", None))
        self.actionFull_Screen.setText(QCoreApplication.translate("MainWindow", u"Full-Screen", None))
        self.actionCenter.setText(QCoreApplication.translate("MainWindow", u"Center", None))
        self.actionMinimum_Size.setText(QCoreApplication.translate("MainWindow", u"Minimum Size", None))
        self.actionMaximum_Size.setText(QCoreApplication.translate("MainWindow", u"Maximum Size", None))
        self.actionRestore.setText(QCoreApplication.translate("MainWindow", u"Restore", None))
        self.actionSSL.setText(QCoreApplication.translate("MainWindow", u"FeView", None))
#if QT_CONFIG(shortcut)
        self.actionSSL.setShortcut(QCoreApplication.translate("MainWindow", u"F1", None))
#endif // QT_CONFIG(shortcut)
        self.actionImage.setText(QCoreApplication.translate("MainWindow", u"Model as Image", None))
        self.actionNode_Label.setText(QCoreApplication.translate("MainWindow", u"Node Label", None))
        self.actionNode_Coordinate.setText(QCoreApplication.translate("MainWindow", u"Node Coordinate", None))
        self.actionLoad.setText(QCoreApplication.translate("MainWindow", u"Load ", None))
        self.actionIsometric.setText(QCoreApplication.translate("MainWindow", u"Isometric", None))
        self.actionxy_zpluss.setText(QCoreApplication.translate("MainWindow", u"XY Plane, Z (+)", None))
        self.actionxy_zminus.setText(QCoreApplication.translate("MainWindow", u"XY Plane, Z (-)", None))
        self.actionXZ_Plane_Y.setText(QCoreApplication.translate("MainWindow", u"XZ Plane, Y (+)", None))
        self.actionXZ_Plane_Y_2.setText(QCoreApplication.translate("MainWindow", u"XZ Plane, Y (-)", None))
        self.actionYZ_Plane_X.setText(QCoreApplication.translate("MainWindow", u"YZ Plane, X (+) ", None))
        self.actionYZ_Plane_X_2.setText(QCoreApplication.translate("MainWindow", u"YZ Plane, X (-) ", None))
        self.actionExport_Report.setText(QCoreApplication.translate("MainWindow", u"Export Report", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionRun_OpenSees.setText(QCoreApplication.translate("MainWindow", u"Run OpenSees", None))
        self.actionApply_Static.setText(QCoreApplication.translate("MainWindow", u"Apply", None))
        self.actionShow_Response.setText(QCoreApplication.translate("MainWindow", u"Response Plot", None))
        self.actionApply_Modal.setText(QCoreApplication.translate("MainWindow", u"Apply", None))
        self.actionApply_dynamic.setText(QCoreApplication.translate("MainWindow", u"Apply", None))
        self.actionShow_Response_dynamic.setText(QCoreApplication.translate("MainWindow", u"Response Plot", None))
        self.actionOpenSees.setText(QCoreApplication.translate("MainWindow", u"OpenSees", None))
#if QT_CONFIG(shortcut)
        self.actionOpenSees.setShortcut(QCoreApplication.translate("MainWindow", u"Shift+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionFeView.setText(QCoreApplication.translate("MainWindow", u"FeView", None))
#if QT_CONFIG(shortcut)
        self.actionFeView.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+A", None))
#endif // QT_CONFIG(shortcut)
        self.actionWith_background.setText(QCoreApplication.translate("MainWindow", u"With background", None))
        self.actionWhite_Background.setText(QCoreApplication.translate("MainWindow", u"White Background", None))
        self.actionMesh_Fiew.setText(QCoreApplication.translate("MainWindow", u"Mesh View", None))
        self.actionSmooth_View.setText(QCoreApplication.translate("MainWindow", u"Smooth View", None))
        self.actionWireframe.setText(QCoreApplication.translate("MainWindow", u"Wiremesh", None))
        self.actionMesh_View_Wiremesh.setText(QCoreApplication.translate("MainWindow", u"Mesh View + Wiremesh", None))
        self.actionSmooth_View_Wiremesh.setText(QCoreApplication.translate("MainWindow", u"Smooth View + Wiremesh", None))
        self.actionMesh_View_2.setText(QCoreApplication.translate("MainWindow", u"Mesh View", None))
        self.actionSmooth_View_2.setText(QCoreApplication.translate("MainWindow", u"Smooth View", None))
        self.actionMesh_View_Wiremesh_undeform.setText(QCoreApplication.translate("MainWindow", u"Mesh View + Wiremesh (undeform)", None))
        self.actionSmooth_View_Wiremesh_undeform.setText(QCoreApplication.translate("MainWindow", u"Smooth View + Wiremesh (undeform)", None))
        self.actionLoad_Setting.setText(QCoreApplication.translate("MainWindow", u"View Load", None))
        self.actionView_load.setText(QCoreApplication.translate("MainWindow", u"View load", None))
        self.actionView_Support.setText(QCoreApplication.translate("MainWindow", u"View Support", None))
        self.actionData_Table.setText(QCoreApplication.translate("MainWindow", u"Data Table", None))
        self.actionData_Table_modal.setText(QCoreApplication.translate("MainWindow", u"Data Table", None))
        self.actionData_Table_dynamic.setText(QCoreApplication.translate("MainWindow", u"Data Table", None))
        self.actionFeView_Website.setText(QCoreApplication.translate("MainWindow", u"FeView Website", None))
        self.actionSSL_Website.setText(QCoreApplication.translate("MainWindow", u"SSL Website", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.menuFIle.setTitle(QCoreApplication.translate("MainWindow", u"FIle", None))
        self.menuExport_Plot.setTitle(QCoreApplication.translate("MainWindow", u"Export Plot", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Setting", None))
        self.menuModel_View_Style.setTitle(QCoreApplication.translate("MainWindow", u"Model Display Style", None))
        self.menuDeform_Model_Display_Style.setTitle(QCoreApplication.translate("MainWindow", u"Deform Model Display Style", None))
        self.menuEdit_2.setTitle(QCoreApplication.translate("MainWindow", u"Analysis", None))
        self.menuStattic_Analysis.setTitle(QCoreApplication.translate("MainWindow", u"Stattic Analysis", None))
        self.menuModal_Analysis.setTitle(QCoreApplication.translate("MainWindow", u"Modal Analysis", None))
        self.Apply_Dyanamic.setTitle(QCoreApplication.translate("MainWindow", u"Dynamic Analysis", None))
        self.menuWindows.setTitle(QCoreApplication.translate("MainWindow", u"Windows", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuAbout.setTitle(QCoreApplication.translate("MainWindow", u"About", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuLabel.setTitle(QCoreApplication.translate("MainWindow", u"Label", None))
        self.dockWidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"Show Result", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"Deformation Scale Factor", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Deformation Scale Factor : ", None))
        self.tb_sef_scale_factor.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Result (Static)", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Contour", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Component", None))
        self.groupBox_6.setTitle("")
        self.btn_apply_static.setText(QCoreApplication.translate("MainWindow", u"Apply", None))
#if QT_CONFIG(tooltip)
        self.btn_response_static.setToolTip(QCoreApplication.translate("MainWindow", u"Respnse Plot ", None))
#endif // QT_CONFIG(tooltip)
        self.btn_response_static.setText(QCoreApplication.translate("MainWindow", u"Resp. Plot", None))
        self.btn_datatable_static.setText(QCoreApplication.translate("MainWindow", u"Data Table", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"Result (Modal Analysis)", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Mode Num.", None))
        self.btn_apply_modal.setText(QCoreApplication.translate("MainWindow", u"Apply", None))
        self.btn_datatable_modal.setText(QCoreApplication.translate("MainWindow", u"Data Table", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Contour", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Component", None))
        self.cb_node_contour_modal.setItemText(0, QCoreApplication.translate("MainWindow", u"Displacement, Ux", None))
        self.cb_node_contour_modal.setItemText(1, QCoreApplication.translate("MainWindow", u"Displacement, Uy", None))
        self.cb_node_contour_modal.setItemText(2, QCoreApplication.translate("MainWindow", u"Displacement, Uz", None))
        self.cb_node_contour_modal.setItemText(3, QCoreApplication.translate("MainWindow", u"Displacement, Uxyz", None))

        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"Result (Transient Analysis)", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Step Num.", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Component", None))
        self.groupBox_14.setTitle("")
        self.btn_datatable_dynamic.setText(QCoreApplication.translate("MainWindow", u"Data Table", None))
#if QT_CONFIG(tooltip)
        self.btn_response_dynamic.setToolTip(QCoreApplication.translate("MainWindow", u"Respnse Plot ", None))
#endif // QT_CONFIG(tooltip)
        self.btn_response_dynamic.setText(QCoreApplication.translate("MainWindow", u"Resp. Plot", None))
        self.btn_apply_dynamic.setText(QCoreApplication.translate("MainWindow", u"Apply", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Info:", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("MainWindow", u"Command", None))
    # retranslateUi

